all_string_combinations=(
"MostFrequentDictionaryWord,FirstDictionaryWordInArticle,LastDictionaryWordInArticle,NumberOfWordsInArticle,DictionaryWordsInArticle,NumberOfDictionaryWordsInFirstPartOfArticle"
"MostFrequentDictionaryWord,FirstDictionaryWordInArticle,LastDictionaryWordInArticle,NumberOfWordsInArticle,DictionaryWordsInArticle,NumberOfDictionaryWordsInLastPartOfArticle"
"MostFrequentDictionaryWord,FirstDictionaryWordInArticle,LastDictionaryWordInArticle,NumberOfWordsInArticle,NumberOfDictionaryWordsInFirstPartOfArticle,NumberOfDictionaryWordsInLastPartOfArticle"
"MostFrequentDictionaryWord,FirstDictionaryWordInArticle,LastDictionaryWordInArticle,DictionaryWordsInArticle,NumberOfDictionaryWordsInFirstPartOfArticle,NumberOfDictionaryWordsInLastPartOfArticle"
"MostFrequentDictionaryWord,FirstDictionaryWordInArticle,NumberOfWordsInArticle,DictionaryWordsInArticle,NumberOfDictionaryWordsInFirstPartOfArticle,NumberOfDictionaryWordsInLastPartOfArticle"
"MostFrequentDictionaryWord,LastDictionaryWordInArticle,NumberOfWordsInArticle,DictionaryWordsInArticle,NumberOfDictionaryWordsInFirstPartOfArticle,NumberOfDictionaryWordsInLastPartOfArticle"
"LeastFrequentDictionaryWord,FirstDictionaryWordInArticle,LastDictionaryWordInArticle,NumberOfWordsInArticle,DictionaryWordsInArticle,NumberOfDictionaryWordsInFirstPartOfArticle"
"LeastFrequentDictionaryWord,FirstDictionaryWordInArticle,LastDictionaryWordInArticle,NumberOfWordsInArticle,DictionaryWordsInArticle,NumberOfDictionaryWordsInLastPartOfArticle"
"LeastFrequentDictionaryWord,FirstDictionaryWordInArticle,LastDictionaryWordInArticle,NumberOfWordsInArticle,NumberOfDictionaryWordsInFirstPartOfArticle,NumberOfDictionaryWordsInLastPartOfArticle"
"LeastFrequentDictionaryWord,FirstDictionaryWordInArticle,LastDictionaryWordInArticle,DictionaryWordsInArticle,NumberOfDictionaryWordsInFirstPartOfArticle,NumberOfDictionaryWordsInLastPartOfArticle"
"LeastFrequentDictionaryWord,FirstDictionaryWordInArticle,NumberOfWordsInArticle,DictionaryWordsInArticle,NumberOfDictionaryWordsInFirstPartOfArticle,NumberOfDictionaryWordsInLastPartOfArticle"
"LeastFrequentDictionaryWord,LastDictionaryWordInArticle,NumberOfWordsInArticle,DictionaryWordsInArticle,NumberOfDictionaryWordsInFirstPartOfArticle,NumberOfDictionaryWordsInLastPartOfArticle"
"MostFrequentDictionaryWord,LeastFrequentDictionaryWord,FirstDictionaryWordInArticle,LastDictionaryWordInArticle,NumberOfWordsInArticle,DictionaryWordsInArticle,NumberOfDictionaryWordsInFirstPartOfArticle"
"MostFrequentDictionaryWord,LeastFrequentDictionaryWord,FirstDictionaryWordInArticle,LastDictionaryWordInArticle,NumberOfWordsInArticle,DictionaryWordsInArticle,NumberOfDictionaryWordsInLastPartOfArticle"
"MostFrequentDictionaryWord,LeastFrequentDictionaryWord,FirstDictionaryWordInArticle,LastDictionaryWordInArticle,NumberOfWordsInArticle,NumberOfDictionaryWordsInFirstPartOfArticle,NumberOfDictionaryWordsInLastPartOfArticle"
"MostFrequentDictionaryWord,LeastFrequentDictionaryWord,FirstDictionaryWordInArticle,LastDictionaryWordInArticle,DictionaryWordsInArticle,NumberOfDictionaryWordsInFirstPartOfArticle,NumberOfDictionaryWordsInLastPartOfArticle"
"MostFrequentDictionaryWord,LeastFrequentDictionaryWord,FirstDictionaryWordInArticle,NumberOfWordsInArticle,DictionaryWordsInArticle,NumberOfDictionaryWordsInFirstPartOfArticle,NumberOfDictionaryWordsInLastPartOfArticle"
"MostFrequentDictionaryWord,LeastFrequentDictionaryWord,LastDictionaryWordInArticle,NumberOfWordsInArticle,DictionaryWordsInArticle,NumberOfDictionaryWordsInFirstPartOfArticle,NumberOfDictionaryWordsInLastPartOfArticle"
"MostFrequentDictionaryWord,FirstDictionaryWordInArticle,LastDictionaryWordInArticle,NumberOfWordsInArticle,DictionaryWordsInArticle,NumberOfDictionaryWordsInFirstPartOfArticle,NumberOfDictionaryWordsInLastPartOfArticle"
"LeastFrequentDictionaryWord,FirstDictionaryWordInArticle,LastDictionaryWordInArticle,NumberOfWordsInArticle,DictionaryWordsInArticle,NumberOfDictionaryWordsInFirstPartOfArticle,NumberOfDictionaryWordsInLastPartOfArticle"
"MostFrequentDictionaryWord,LeastFrequentDictionaryWord,FirstDictionaryWordInArticle,LastDictionaryWordInArticle,NumberOfWordsInArticle,DictionaryWordsInArticle,NumberOfDictionaryWordsInFirstPartOfArticle,NumberOfDictionaryWordsInLastPartOfArticle")
declare -a available_metrices=( "ChebyshevMetric" "EukidesMetric" "ManhattanMetric")
declare -a available_similarities=( "ExtendedNGramSimilarity" "JaccardSimilarity" "NGramSimilarity")
declare -a available_k=("1" "5" "10" "15" "20" "25" "30");

parallel --eta -j+0 --results outputs/string/ java -jar out/artifacts/Sztuczna_jar/Sztuczna.jar \
	-k {1} \
	-p {2} \
	-m {3} \
	-s {4} \
	::: ${available_k[@]} ::: ${all_string_combinations[@]} ::: ${available_metrices[@]} ::: ${available_similarities[@]};
